export const FETCHING_STUDENTS_SUCCESS = 'FETCHING_STUDENTS_SUCCESS';
export const SUBMIT_STUDENTS_SUCCESS = 'SUBMIT_STUDENTS_SUCCESS';
export const UPDATE_STUDENTS_SUCCESS = 'UPDATE_STUDENTS_SUCCESS';
export const DELETE_STUDENTS_SUCCESS = 'DELETE_STUDENTS_SUCCESS';
